# Generated by Django 5.0.4 on 2024-05-06 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_goal_image_goal_reflection_goal_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='description',
        ),
    ]
