# Generated by Django 5.0.4 on 2024-05-06 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_goal_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='image',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='reflection',
        ),
    ]
